/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module digital_lock_controller(clk, reset, enter, digit, unlock, alarm);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  output alarm;
  wire alarm;
  input clk;
  wire clk;
  input [3:0] digit;
  wire [3:0] digit;
  input enter;
  wire enter;
  input reset;
  wire reset;
  output unlock;
  wire unlock;
  sky130_fd_sc_hd__clkinv_1 _08_ (
    .A(reset),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nand4bb_1 _09_ (
    .A_N(digit[1]),
    .B_N(digit[3]),
    .C(digit[0]),
    .D(digit[2]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _10_ (
    .A(_01_),
    .SLEEP(reset),
    .X(unlock)
  );
  sky130_fd_sc_hd__o21bai_1 _11_ (
    .A1(_01_),
    .A2(enter),
    .B1_N(reset),
    .Y(_06_)
  );
  sky130_fd_sc_hd__a21oi_1 _12_ (
    .A1(enter),
    .A2(_05_),
    .B1(_06_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _13_ (
    .A(_00_),
    .SLEEP(reset),
    .X(alarm)
  );
  sky130_fd_sc_hd__nor3b_1 _14_ (
    .A(reset),
    .B(enter),
    .C_N(_00_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__a31o_1 _15_ (
    .A1(_04_),
    .A2(enter),
    .A3(_05_),
    .B1(_07_),
    .X(_03_)
  );
  sky130_fd_sc_hd__dfxtp_1 _16_ (
    .CLK(clk),
    .D(_02_),
    .Q(_01_)
  );
  sky130_fd_sc_hd__dfxtp_1 _17_ (
    .CLK(clk),
    .D(_03_),
    .Q(_00_)
  );
endmodule
