/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

(* top =  1  *)
(* src = "rtl/digital_lock_controller.sv:1.1-30.10" *)
module digital_lock_controller(clk, reset, enter, digit, unlock, alarm);
  wire _0_;
  (* src = "rtl/digital_lock_controller.sv:19.17-19.30" *)
  wire _1_;
  wire _2_;
  wire _3_;
  (* src = "rtl/digital_lock_controller.sv:7.18-7.23" *)
  output alarm;
  reg alarm;
  (* src = "rtl/digital_lock_controller.sv:2.18-2.21" *)
  input clk;
  wire clk;
  (* src = "rtl/digital_lock_controller.sv:5.24-5.29" *)
  input [3:0] digit;
  wire [3:0] digit;
  (* src = "rtl/digital_lock_controller.sv:4.18-4.23" *)
  input enter;
  wire enter;
  (* src = "rtl/digital_lock_controller.sv:3.18-3.23" *)
  input reset;
  wire reset;
  (* src = "rtl/digital_lock_controller.sv:6.18-6.24" *)
  output unlock;
  reg unlock;
  assign _2_ = digit[0] & ~(digit[1]);
  assign _3_ = digit[3] | ~(digit[2]);
  assign _0_ = _3_ | ~(_2_);
  assign _1_ = _2_ & ~(_3_);
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/digital_lock_controller.sv:12.5-28.8" *)
  always @(posedge clk, posedge reset)
    if (reset) unlock <= 1'h0;
    else if (enter) unlock <= _1_;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/digital_lock_controller.sv:12.5-28.8" *)
  always @(posedge clk, posedge reset)
    if (reset) alarm <= 1'h0;
    else if (enter) alarm <= _0_;
endmodule
